---
apiVersion: v1
kind: Namespace
metadata:
    name: influxdb
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
    labels:
        app: influxdb
    name: influxdb
    namespace: influxdb
spec:
    replicas: 1
    selector:
        matchLabels:
            app: influxdb
    serviceName: influxdb
    template:
        metadata:
            labels:
                app: influxdb
        spec:
            containers:
              - image: influxdb:2.0.6
                name: influxdb
                ports:
                  - containerPort: 8086
                    name: influxdb
                env:
                  - name: DOCKER_INFLUXDB_INIT_MODE
                    value: "setup"
                  - name: DOCKER_INFLUXDB_INIT_USERNAME
                    value: "my-user"
                  - name: DOCKER_INFLUXDB_INIT_PASSWORD
                    value: "my-password"
                  - name: DOCKER_INFLUXDB_INIT_ORG
                    value: "my-org"
                  - name: DOCKER_INFLUXDB_INIT_BUCKET
                    value: "my-bucket"
                  - name: DOCKER_INFLUXDB_INIT_RETENTION
                    value: "1w" 
                  - name: DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
                    value: "my-super-secret-auth-token"
---
apiVersion: v1
kind: Service
metadata:
    name: influxdb
    namespace: influxdb
spec:
    ports:
      - name: influxdb
        port: 8086
        targetPort: 8086
    selector:
        app: influxdb
    type: NodePort
