apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-yourname
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/yourname"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-yourname
spec:
  volumeName: pv-yourname
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Mi
--- 
apiVersion: v1
kind: Service
metadata:
  name: yourname
spec:
  type: NodePort
  ports:
  - port: 3306
  selector:
    app: mysql-yourname
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yourname
spec:
  selector:
    matchLabels:
      app: mysql-yourname
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-yourname
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: bSqdYYqsqU5VPj2g
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: pvc-yourname
